model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "/home/bluvoll/stable-diffusion-webui-reForge/models/Stable-diffusion/Chenkin-RF-0.3-Final-000001.safetensors"
train_data_dir = "/home/bluvoll/Escritorio/anime/kanojos/"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "Kanojos-Aki-trainer"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 1
save_state = false
max_train_epochs = 30
train_batch_size = 12
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.00004
unet_lr = 0.00004
text_encoder_lr = 0
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 5
loss_type = "l2"
lr_scheduler_num_cycles = 2
optimizer_type = "pytorch_optimizer.CAME"
network_module = "lycoris.kohya"
network_dim = 32
network_alpha = 32
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
max_token_length = 255
caption_dropout_rate = 0.1
caption_tag_dropout_rate = 0.1
flow_model = true
flow_use_ot = true
flow_timestep_distribution = "uniform"
flow_uniform_static_ratio = 2
contrastive_flow_matching = false
cfm_lambda = 0.05
seed = 1337
mixed_precision = "bf16"
full_bf16 = true
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
persistent_data_loader_workers = true
network_args = [ "conv_dim=32", "conv_alpha=32", "dropout=0", "algo=locon" ]
optimizer_args = [ "weight_decay=0.03" ]
