<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue"
import { ElMessage, ElMessageBox } from "element-plus"
import { animaFastApi, type AnimaFastStatus } from "../api/animaFast"
import TrainingPage from "./TrainingPage.vue"

const status=ref<AnimaFastStatus>({state:"unknown",feature_enabled:true});const loading=ref(false);const logs=ref<string[]>([]);const progress=ref(0);const phase=ref("");let timer:number|undefined;let logSource:EventSource|undefined;let progressSource:EventSource|undefined
const ready=computed(()=>status.value.state==="ready");const working=computed(()=>["installing","auditing"].includes(status.value.state));const label=computed(()=>({ready:"插件已就绪",installing:"安装中",auditing:"审计中",broken:"需要修复",installed_unverified:"等待审计",unknown:"状态未知",disabled:"功能未启用"}[status.value.state]))
function closeStreams(){logSource?.close();progressSource?.close();logSource=undefined;progressSource=undefined}
function streams(taskId:string,logUrl?:string,progressUrl?:string){closeStreams();logSource=new EventSource(logUrl||`/api/plugins/anima-lora/install/log/stream/${taskId}`);logSource.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.text)logs.value.push(d.text);if(d.done)logSource?.close()}catch{logs.value.push(e.data)}};progressSource=new EventSource(progressUrl||`/api/plugins/anima-lora/install/progress/stream/${taskId}`);progressSource.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==="progress"){progress.value=Number(d.percent||0);phase.value=d.message||d.phase||""}if(d.done||d.type==="done")progressSource?.close()}catch{}}}
async function refresh(){try{status.value=await animaFastApi.status();const id=status.value.facts?.task_id;if(id&&working.value&&!logSource)streams(id)}catch(e){ElMessage.error(e instanceof Error?e.message:"状态读取失败")}}
async function install(repair=false){try{await ElMessageBox.confirm("Anima Fast 会下载独立 Python 环境和数 GB 依赖，并要求 NVIDIA GPU。确认继续？",repair?"修复插件":"安装插件",{type:"warning"});loading.value=true;logs.value=[];progress.value=0;const d=repair?await animaFastApi.repair():await animaFastApi.install();if(d.already_ready){status.value=d.status||status.value;return ElMessage.success("插件已就绪")}if(d.task_id)streams(d.task_id,d.log_stream||d.log_stream_url,d.progress_stream||d.progress_stream_url);await refresh();ElMessage.success("安装任务已启动")}catch(e){if(e!=="cancel"&&e!=="close")ElMessage.error(e instanceof Error?e.message:"操作失败")}finally{loading.value=false}}
onMounted(async()=>{await refresh();timer=window.setInterval(refresh,2000)});onBeforeUnmount(()=>{window.clearInterval(timer);closeStreams()})
</script>
<template><TrainingPage v-if="ready" title="Anima LoRA Fast" area="anima-lora-fast" schema-name="anima-lora-fast"/><div v-else class="fast-page"><section class="fast-intro"><span class="eyebrow">ANIMA FAST RUNTIME</span><h1>Anima LoRA Fast</h1><p>独立运行环境、安装审计与高性能训练入口。</p><div class="fast-state" :data-state="status.state"><span>{{label}}</span><strong>{{status.state}}</strong></div><div v-if="status.facts?.audit?.errors?.length" class="audit-errors"><strong>环境审计</strong><p v-for="error in status.facts.audit.errors" :key="error">{{error}}</p></div><div class="fast-actions"><button class="primary-action" :disabled="loading||working||!status.feature_enabled" @click="install(false)">{{working?'安装进行中':'安装插件'}}</button><button v-if="status.state==='broken'" class="secondary-action" :disabled="loading" @click="install(true)">修复环境</button></div></section><aside class="install-console"><header><span>{{phase||"安装日志"}}</span><b>{{progress}}%</b></header><div class="install-progress"><i :style="{width:`${progress}%`}" /></div><pre>{{logs.length?logs.join('\n'):'等待安装任务输出…'}}</pre></aside></div></template>
