<script setup lang="ts">
import { computed, ref } from "vue"
import { ElMessage, ElMessageBox } from "element-plus"
import { datasetApi, type ChangedItem, type DatasetItem } from "../api/dataset"
const path=ref("");const root=ref("");const items=ref<DatasetItem[]>([]);const categories=ref<{name:string;value:string;count:number}[]>([]);const category=ref("");const query=ref("");const selected=ref("");const caption=ref("");const append=ref("");const remove=ref("");const loading=ref(false)
const filtered=computed(()=>items.value.filter(i=>(!category.value||i.category===category.value)&&(!query.value||i.caption.toLowerCase().includes(query.value.toLowerCase()))));const current=computed(()=>items.value.find(i=>i.relative_path===selected.value))
function choose(item:DatasetItem){selected.value=item.relative_path;caption.value=item.caption}function apply(changes:ChangedItem[]){const map=new Map(changes.map(i=>[i.image,i]));items.value=items.value.map(i=>{const c=map.get(i.relative_path);return c?{...i,caption:c.caption,tags:c.tags,caption_exists:c.caption_exists}:i});if(current.value)caption.value=current.value.caption}
async function scan(){if(!path.value.trim())return;loading.value=true;try{const d=await datasetApi.scan(path.value);root.value=d.root;path.value=d.root;items.value=d.items;categories.value=d.categories;if(d.items[0])choose(d.items[0]);ElMessage.success(`已加载 ${d.total} 张图片`)}catch(e){ElMessage.error(e instanceof Error?e.message:"扫描失败")}finally{loading.value=false}}
async function save(){if(!current.value)return;try{const d=await datasetApi.save(root.value,current.value.relative_path,caption.value);apply([d]);ElMessage.success("Caption 已保存")}catch(e){ElMessage.error(e instanceof Error?e.message:"保存失败")}}
async function batch(){if(!filtered.value.length)return;try{await ElMessageBox.confirm(`将修改当前筛选的 ${filtered.value.length} 张图片，是否继续？`,"批量编辑");const d=await datasetApi.batch({root:root.value,images:filtered.value.map(i=>i.relative_path),append:append.value.split(",").map(x=>x.trim()).filter(Boolean),remove:remove.value.split(",").map(x=>x.trim()).filter(Boolean)});apply(d.items);ElMessage.success(`已修改 ${d.changed} 张图片`)}catch(e){if(e!=="cancel"&&e!=="close")ElMessage.error(e instanceof Error?e.message:"批量编辑失败")}}
async function history(kind:"undo"|"redo"){try{const d=await datasetApi[kind](root.value);apply(d.items);ElMessage.success(kind==="undo"?"已撤回":"已重做")}catch(e){ElMessage.error(e instanceof Error?e.message:"操作失败")}}
</script>
<template><div class="dataset-page"><aside class="dataset-side"><span class="eyebrow">DATASET EDITOR</span><h1>标签编辑器</h1><label>数据集目录<input v-model="path" @keyup.enter="scan" /></label><button class="primary-action" :disabled="loading" @click="scan">{{loading?'扫描中…':'扫描数据集'}}</button><label>分类<select v-model="category"><option value="">全部</option><option v-for="c in categories" :key="c.value" :value="c.value">{{c.name}} ({{c.count}})</option></select></label><label>Caption 筛选<input v-model="query" /></label><div class="batch-box"><strong>批量编辑当前筛选</strong><input v-model="append" placeholder="追加 tag，逗号分隔"/><input v-model="remove" placeholder="删除 tag，逗号分隔"/><button @click="batch">应用到 {{filtered.length}} 张</button></div></aside><main class="dataset-gallery"><header><strong>{{filtered.length}} / {{items.length}} 张图片</strong><div><button :disabled="!root" @click="history('undo')">撤回</button><button :disabled="!root" @click="history('redo')">重做</button></div></header><div class="image-grid"><button v-for="item in filtered" :key="item.relative_path" :class="{active:selected===item.relative_path}" @click="choose(item)"><img :src="item.image_url" :alt="item.name" loading="lazy"/><span>{{item.name}}</span></button></div></main><aside class="caption-panel"><div v-if="current"><img :src="current.image_url" :alt="current.name"/><strong>{{current.relative_path}}</strong><textarea v-model="caption" rows="10"/><button class="primary-action" @click="save">保存 Caption</button></div><p v-else>扫描并选择图片后开始编辑。</p></aside></div></template>
