<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive } from "vue"
import { ElMessage } from "element-plus"
import { storeToRefs } from "pinia"
import { useTaggerStore } from "../stores/tagger"

const models = ["wd14-convnextv2-v2", "wd-convnext-v3", "wd-swinv2-v3", "wd-vit-v3", "wd14-swinv2-v2", "wd14-vit-v2", "wd14-moat-v2", "wd-eva02-large-tagger-v3", "wd-vit-large-tagger-v3", "cl_tagger_1_01"]
const form = reactive({ path: "", interrogator_model: models[0], threshold: .35, character_threshold: .6, add_rating_tag: false, add_model_tag: false, additional_tags: "", exclude_tags: "", escape_tag: true, batch_input_recursive: false, batch_output_action_on_conflict: "copy", replace_underscore: true, download_endpoint: "", replace_underscore_excludes: "0_0, (o)_(o), +_+, +_-, ._., <o>_<o>, <|>_<|>, =_=, >_<, 3_3, 6_9, >_o, @_@, ^_^, o_o, u_u, x_x, |_|, ||_||" })
const store = useTaggerStore()
const { status, error, submitting, busy } = storeToRefs(store)
const downloadPercent = computed(() => status.value.download.percent || (status.value.download.total ? Math.round(status.value.download.current / status.value.download.total * 100) : 0))
const taggingPercent = computed(() => status.value.tagging.total ? Math.round(status.value.tagging.current / status.value.tagging.total * 100) : 0)
let timer: number | undefined
async function start() { if (!form.path.trim()) return ElMessage.error("请先填写图片文件夹路径"); try { await store.start({ ...form, path: form.path.replaceAll("\\", "/") }); ElMessage.success("打标任务已提交") } catch (e) { ElMessage.error(e instanceof Error ? e.message : "提交失败") } }
async function invoke(kind: "prefetch" | "cancel" | "reset") { try { if (kind === "prefetch") await store.prefetch(form.interrogator_model, form.download_endpoint); else await store[kind](); ElMessage.success(kind === "cancel" ? "已请求中止" : kind === "reset" ? "状态已重置" : "模型下载已开始") } catch (e) { ElMessage.error(e instanceof Error ? e.message : "操作失败") } }
onMounted(async () => { await store.refresh(); timer = window.setInterval(store.refresh, 1200) })
onBeforeUnmount(() => window.clearInterval(timer))
</script>

<template><div class="tagger-page"><section class="tagger-form"><header><span class="eyebrow">DATASET TAGGER</span><h1>Tagger 标注工具</h1><p>选择模型和图片目录，自动生成同名 caption 文件。</p></header><div class="tagger-grid"><label>Tagger 模型<select v-model="form.interrogator_model"><option v-for="model in models" :key="model">{{ model }}</option></select></label><label>图片文件夹<input v-model="form.path" placeholder="D:/datasets/images" /></label><label>一般标签阈值<input v-model.number="form.threshold" type="number" min="0" max="1" step="0.05" /></label><label>角色标签阈值<input v-model.number="form.character_threshold" type="number" min="0" max="1" step="0.05" /></label><label>附加提示词<input v-model="form.additional_tags" /></label><label>排除标签<input v-model="form.exclude_tags" /></label><label>下载加速源<input v-model="form.download_endpoint" placeholder="留空使用默认 Hugging Face" /></label><label>已有 Caption<select v-model="form.batch_output_action_on_conflict"><option value="ignore">忽略</option><option value="copy">覆盖</option><option value="prepend">前置</option></select></label></div><div class="check-row"><label><input v-model="form.batch_input_recursive" type="checkbox" />递归搜索</label><label><input v-model="form.replace_underscore" type="checkbox" />下划线转空格</label><label><input v-model="form.escape_tag" type="checkbox" />转义括号</label><label><input v-model="form.add_rating_tag" type="checkbox" />添加等级标签</label><label><input v-model="form.add_model_tag" type="checkbox" />添加模型标签</label></div></section>
<aside class="tagger-status"><span class="task-status">{{ status.phase }}</span><h2>{{ status.message || "配置参数后点击启动" }}</h2><p v-if="error">{{ error }}</p><div class="meter"><header><span>模型下载</span><b>{{ downloadPercent }}%</b></header><div><i :style="{ width: `${downloadPercent}%` }" /></div><small>{{ status.download.filename || "尚未开始" }}</small></div><div class="meter"><header><span>图片打标</span><b>{{ taggingPercent }}%</b></header><div><i :style="{ width: `${taggingPercent}%` }" /></div><small>{{ status.tagging.current }} / {{ status.tagging.total }} {{ status.tagging.filename }}</small></div><div class="tagger-actions"><button v-if="busy" class="danger-action" :disabled="submitting" @click="invoke('cancel')">中止任务</button><button v-else class="primary-action" :disabled="submitting" @click="start">启动打标</button><button class="secondary-action" :disabled="submitting || status.phase === 'tagging'" @click="invoke('prefetch')">预下载模型</button><button class="secondary-action" :disabled="submitting" @click="invoke('reset')">重置状态</button></div></aside></div></template>
